apiVersion: v1
kind: Service
metadata:
  name: civo-docs
  labels:
    app.kubernetes.io/name: civo-docs
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app.kubernetes.io/name: civo-docs